pipeline {
  agent none

  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        echo 'Running Back-end stage...'
        sh 'echo "Hello from Back-end (Maven + Java 11)!"'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        echo 'Running Front-end stage...'
        sh 'echo "Hello from Front-end (Node.js)!"'
      }
    }
  }
}
